version: "3.7"

services:
  router:
    build:
      context: .
      dockerfile: docker/router.dockerfile
    ports:
      - "${PORT:-80}:80"
      - "${TLS_PORT:-443}:443"
    volumes:
      - './cert/:/app/cert/'
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: docker/server.dockerfile
    environment:
      PORT: 80
      db_host: postgres
      db_port: 5432
      db_user: postgres
      db_password: e72a7e3456874163b3b715297be8a731
      db_database: nft-bbs
    depends_on:
      - postgres

  postgres:
    image: "postgres:alpine"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: e72a7e3456874163b3b715297be8a731
      POSTGRES_DB: nft-bbs
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'

volumes:
  postgres-data:
