version: "3.7"

services:
  router:
    image: noe132/port-router:latest
    ports:
      - "${PORT:-35572}:80"
    environment:
      PORT_SERVER_HOST: 'server'
    depends_on:
      - server

  server:
    image: noe132/port-server:latest
    volumes:
      - './packages/server/config.sample.yml:/app/packages/server/config.yml'
    depends_on:
      - postgres

  postgres:
    image: "postgres:14-alpine"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: e72a7e3456874163b3b715297be8a731
      POSTGRES_DB: port
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'

volumes:
  postgres-data:
