services:
  router:
    image: noe132/port-router:latest
    ports:
      - "${PORT:-35572}:80"
    volumes:
      - './docker/router.nginx.conf:/etc/nginx/nginx.conf'
    environment:
      PORT_SERVER_HOST: 'server'
    depends_on:
      - server

  server:
    image: noe132/port-server:latest
    volumes:
      - './packages/server/config.yml:/app/packages/server/config.yml:ro'
    environment:
      DB_HOST: 'postgres'
      DB_PORT: 5432
      DB_USER: 'postgres'
      DB_PASSWORD: 'e72a7e3456874163b3b715297be8a731'
      DB_DATABASE: 'port'
    depends_on:
      - postgres

  postgres:
    image: "postgres:14-alpine"
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'e72a7e3456874163b3b715297be8a731'
      POSTGRES_DB: 'port'
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'

volumes:
  postgres-data:
