version: "3.7"

services:
  router:
    image: dockerhub.qingcloud.com/pressone/nft-bbs-router:latest
    ports:
      - "${PORT:-35572}:80"
    volumes:
      - './docker/router.nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - server

  server:
    image: dockerhub.qingcloud.com/pressone/nft-bbs-server:latest
    volumes:
      - './packages/server/config.yml:/app/packages/server/config.yml'
    environment:
      PORT: 80
    depends_on:
      - postgres

  postgres:
    image: "postgres:14-alpine"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: e72a7e3456874163b3b715297be8a731
      POSTGRES_DB: port
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'

volumes:
  postgres-data:
